/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asiainfo_biframe_privacyprotection_util_DecryptContext */

#ifndef _Included_com_asiainfo_biframe_privacyprotection_util_DecryptContext
#define _Included_com_asiainfo_biframe_privacyprotection_util_DecryptContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asiainfo_biframe_privacyprotection_util_DecryptContext
 * Method:    c_init_decrypt_context
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_asiainfo_biframe_privacyprotection_util_DecryptContext_c_1init_1decrypt_1context
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_asiainfo_biframe_privacyprotection_util_DecryptContext
 * Method:    c_decrypt
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_asiainfo_biframe_privacyprotection_util_DecryptContext_c_1decrypt
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_asiainfo_biframe_privacyprotection_util_DecryptContext
 * Method:    c_destory_decrypt_context
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_asiainfo_biframe_privacyprotection_util_DecryptContext_c_1destory_1decrypt_1context
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
